# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 056e70e48ec04fcff14ab3a590a47a5fdf95b05dec88d34f7f0eaf6d6dc3cf3a430d6fd66022211111457b7ab30665c027233f52ffefa51d901519f50491a2ec

test:
  secret_key_base: bdf257b4ebd70a8f5e82cf743e8551b3e9cfe17288b363432dec28e1792b067c043fb27c2569de069d82e0ca44b6004629c8fe8346f3153931c0529c490d23a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
